name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]

    steps:
    - uses: actions/checkout@v2
    - run: cargo test

  fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]

    steps:
    - uses: actions/checkout@v2
    - run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]

    steps:
    - uses: actions/checkout@v2
    - run: cargo clippy
